SELECT * FROM customer_shopping_behavior

--Q1. What is the total revenue generated by male vs. female customers?
SELECT Gender, SUM(Purchase_Amount_USD) as revenue
FROM customer_shopping_behavior
GROUP BY Gender


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT Customer_ID, Purchase_Amount_USD 
FROM customer_shopping_behavior
WHERE Discount_Applied = 'Yes' AND Purchase_Amount_USD >= (SELECT AVG(Purchase_Amount_USD) FROM customer_shopping_behavior)

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 Item_Purchased, ROUND(AVG(Review_Rating),2) AS "Average Product Rating"
FROM customer_shopping_behavior
GROUP BY Item_Purchased
ORDER BY AVG(Review_Rating) DESC 

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT Shipping_Type, 
ROUND(AVG(Purchase_Amount_USD),2) AS AVG_Purchase_Amount
FROM customer_shopping_behavior
WHERE Shipping_Type IN ('Standard','Express')
GROUP BY Shipping_Type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT Subscription_Status,
       COUNT(Customer_ID) AS Total_Customers,
       ROUND(AVG(Purchase_Amount_USD),2) AS AVG_Spend,
       ROUND(SUM(Purchase_Amount_USD),2) AS Total_Revenue
FROM customer_shopping_behavior
GROUP BY Subscription_Status
ORDER BY Total_Revenue,AVG_Spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 Item_Purchased,
       ROUND(100.0 * SUM(CASE WHEN Discount_Applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS Discount_Rate
FROM customer_shopping_behavior
GROUP BY Item_Purchased
ORDER BY Discount_Rate DESC

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
WITH Customer_Type AS (
SELECT Customer_ID, Previous_Purchases,
CASE 
    WHEN Previous_Purchases = 1 THEN 'New'
    WHEN Previous_Purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS Customer_Segment
FROM customer_shopping_behavior)

SELECT Customer_Segment,count(*) AS "Number of Customers" 
FROM Customer_Type 
group by Customer_Segment;

--Q8. What are the top 3 most purchased products within each category? 
WITH Item_Counts AS (
    SELECT Category,
           Item_Purchased,
           COUNT(Customer_ID) AS Total_Orders,
           ROW_NUMBER() OVER (PARTITION BY Category ORDER BY COUNT(Customer_ID) DESC) AS Item_Rank
FROM customer_shopping_behavior
    GROUP BY Category, Item_Purchased
)
SELECT Item_Rank,Category, Item_Purchased, Total_Orders
FROM Item_Counts
WHERE Item_Rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT Subscription_Status,
       COUNT(Customer_ID) AS Repeat_Buyers
FROM customer_shopping_behavior
WHERE Previous_Purchases > 5
GROUP BY Subscription_Status;

--Q10. What is the revenue contribution of each age group? 
WITH Age_Group AS (
    SELECT
        *,
        CASE 
            WHEN Age < 18 THEN 'Under 18'
            WHEN Age BETWEEN 18 AND 25 THEN '18-25'
            WHEN Age BETWEEN 26 AND 35 THEN '26-35'
            WHEN Age BETWEEN 36 AND 50 THEN '36-50'
            ELSE '50+'
        END AS Age_Group_Category
    FROM customer_shopping_behavior
)

SELECT 
    Age_Group_Category AS Age_Group,
    SUM(Purchase_Amount_USD) AS Total_Revenue
FROM Age_Group
GROUP BY Age_Group_Category
ORDER BY Total_Revenue DESC;
